apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-sample-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs-sample-app
    spec:
      containers:
      - name: nodejs-sample-app
        image: registry.gitlab.com/madhavikhatawakar/nodejs-sample-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: registry.gitlab.com
